apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7-debian
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pass123"
        - name: MYSQL_DATABASE
          value: "paperdb"
        - name: MYSQL_ROOT_HOST
          value: "%"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "user"
        ports:
        - containerPort: 3306
        args:
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP

